version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file: ./api/.env
    volumes:
      - /app/node_modules 
      - ./api:/app 
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    env_file: ./client/.env
    volumes:
      - /app/node_modules
      - ./client:/app 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
        - api
    ports:
      - "5000:80"